### ISSUE TITLE
How to combine BPT with sequence parallel?

### ISSUE THREAD

**Issue by fanghgit** [lhao499/blockwise-parallel-transformer#1]
Thanks very much for sharing your work! I wonder if BPT is compatible with sequence parallelism. From the related work section, I find the statement _"This creates an orthogonal relationship between our method and sequence parallelism, allowing for straightforward combination"._ However, this combination is not that straightforward to me. Please see my comments below.

To my understanding, BPT breaks long sequence into small sequences and feed these small sequences sequentially to attn+layernorm+MLP. Recent LLM training pipeline usually apply sequence parallelism(https://arxiv.org/pdf/2205.05198.pdf) to the layernorm part therefore do layernorm **simultaneously** amony GPUs. This seems to break the connection between attention and MLP when using BPT. I wonder if it is possible to seamlessly combine BPT with sequence parallelism when layernorm is considered.

**Comment by lhao499** [comment]
Closing as completed. Feel free to reopen.
