### ISSUE TITLE
[Question] Add a normalization layer between Attention and FFN?

### ISSUE THREAD

**Issue by findmyway** [lhao499/blockwise-parallel-transformer#8]
In the original paper, it assumes that, _"The computation for a query block is given by:"_

![image](https://github.com/lhao499/blockwise-parallel-transformer/assets/5612003/3c396bf9-da77-4cc0-b77d-0506cf200b49)

If we want to add a normalization layer to the input of FFN,  then it will break the end-to-end fusion, am I right?

Based on my understanding, normalizations like `RMSNorm` require access to the whole tensor to calculate some statistics first.

**Comment by lhao499** [comment]
If the normalization layer is applied on hidden dimension, then it it still blockwise independent.

**Comment by lhao499** [comment]
The code provided follows LLaMA and GPT architectures' layer norms.  
If you would like to add additional normalization layer, you can add it around [blockwise_compute_ffn](https://github.com/lhao499/blockwise-parallel-transformer/blob/d6532bcea17d4edf9294a3c5557ae984f01a8fff/llamabpt/llamabpt.py#L846).

**Comment by findmyway** [comment]
I see. Thanks for your explanation!

**Comment by stgzr** [comment]
How about the activation function in FFN? Since it is a nonlinear function.
